var canvas,context,width,height;function init(){canvas=document.querySelector("canvas");context=canvas.getContext("2d");canvas.width=width=window.innerWidth;canvas.height=height=window.innerHeight;player.x=30;player.y=height/2;player.health=15;player.ammo=20;addEventListener("keydown",keydown);addEventListener("keyup",keyup);addEventListener("keyup",function(a){80==a.keyCode?paused=!paused:"Space"==a.code&&player.fire()});requestAnimationFrame(animate)}
function end_game(){playing=!1;alert("game over. score: "+score)}var keys={up:!1,down:!1,left:!1,right:!1};function keydown(a){a.preventDefault();switch(a.keyCode){case 38:case 87:keys.up=!0;break;case 40:case 83:keys.down=!0;break;case 37:case 65:keys.left=!0;break;case 39:case 68:keys.right=!0}}function keyup(a){switch(a.keyCode){case 38:case 87:keys.up=!1;break;case 40:case 83:keys.down=!1;break;case 37:case 65:keys.left=!1;break;case 39:case 68:keys.right=!1}}
var score=0,monsters=[],bullets=[],objects=[],texts=[],player={x:null,y:null,ammo:null,health:null,speed:.2,pose:0,move_time:0,pose_delay:250,offset_x:8,offset_y:15,fire:function(){0<this.ammo?(bullets.push(new Bullet(this.x+this.offset_x,this.y)),this.ammo--):texts.push(new Text("no ammo!",this.x,this.y,1500,{r:255,g:140,b:0}))},collision:function(a){this.health-=void 0==a?1:a},update:function(a){var b=keys.left?-1:0;b+=keys.right?1:0;var c=keys.up?-1:0;c+=keys.down?1:0;this.x+=b*this.speed*a;this.y+=
c*this.speed*a;this.x=Math.max(this.x,this.offset_x);this.x=Math.min(this.x,200-this.offset_x);this.y=Math.max(this.y,this.offset_y);this.y=Math.min(this.y,height-this.offset_y);keys.left||keys.right||keys.up||keys.down?(this.move_time+=a,this.pose=0==Math.floor(this.move_time/this.pose_delay)%2?2:1):this.pose=this.move_time=0;0>=this.health&&end_game()}};function Bullet(a,b){this.x=a;this.y=b;this.active=!0}Bullet.prototype.speed=.3;
Bullet.prototype.update=function(a){this.x+=a*this.speed;this.x>width&&(this.active=!1)};Bullet.prototype.collision=function(){this.active=!1};function Monster(a,b){this.x=a;this.y=b;this.speed=.025+.025*Math.random();this.lifetime=this.pose_time=this.pose=0;this.active=!0}Monster.prototype.pose_delay=167;Monster.prototype.offset=15;
Monster.prototype.update=function(a){var b=this;this.x-=a*this.speed;var c=bullets.filter(function(a){return a.x>b.x-b.offset&&a.y>b.y-b.offset&&a.x<b.x+b.offset&&a.y<b.y+b.offset});0<c.length&&(c.forEach(function(a){a.collision()}),score++,.15>Math.random()?objects.push(new Ammo_box(200*Math.random(),Math.random()*height)):Math.random()<1/17&&objects.push(new Health_box(200*Math.random(),Math.random()*height)),this.active=!1);Math.abs(player.x-this.x)<this.offset+player.offset_x&&Math.abs(player.y-
this.y)<this.offset+player.offset_y&&(texts.push(new Text("-1 health",this.x,this.y,1500,{r:220,g:20,b:60})),player.collision(),this.active=!1);0>this.x&&(this.active=!1,score-=10);this.pose_time+=a;this.pose_time>=this.pose_delay&&(this.pose_time=0,this.pose++,this.pose%=4)};function Big_monster(a,b){this.x=a;this.y=b;this.health=this.max_health;this.pose_time=this.pose=0;this.active=!0}Big_monster.prototype.speed=.01;Big_monster.prototype.pose_delay=167;Big_monster.prototype.offset=30;
Big_monster.prototype.max_health=10;
Big_monster.prototype.update=function(a){var b=this;this.pose_time+=a;this.pose_time>=this.pose_delay&&(this.pose_time=0,this.pose++,this.pose%=4);this.x-=this.speed*a;a=bullets.filter(function(a){return a.x>b.x-b.offset&&a.x<b.x+b.offset&&a.y>b.y-b.offset&&a.y<b.y+b.offset});0<a.length&&(this.health--,0>=this.health&&(this.active=!1,score+=15,objects.push(new Health_box(200*Math.random(),Math.random()*height)),objects.push(new Health_box(200*Math.random(),Math.random()*height)),objects.push(new Health_box(200*
Math.random(),Math.random()*height))),a.forEach(function(a){a.collision()}));Math.abs(this.x-player.x)<this.offset+player.offset_x&&Math.abs(this.y-player.y)<this.offset+player.offset_y&&(player.health=0)};var spawn_time=null;function spawn_monster(a){.1>Math.random()&&50<score?monsters.push(new Big_monster(width,30+Math.random()*(height-60))):monsters.push(new Monster(width,15+Math.random()*(height-30)));spawn_time=a+1500*Math.random()}function Ammo_box(a,b){this.x=a;this.y=b;this.active=!0}
Ammo_box.prototype.offset=10;Ammo_box.prototype.update=function(a){this.x>player.x-this.offset-player.offset_x&&this.y>player.y-this.offset-player.offset_y&&this.x<player.x+this.offset+player.offset_x&&this.y<player.y+this.offset+player.offset_y&&(this.active=!1,player.ammo+=10,texts.push(new Text("+10 ammo",this.x,this.y,1500)))};function Health_box(a,b){this.x=a;this.y=b;this.active=!0}Health_box.prototype.offset=10;
Health_box.prototype.update=function(a){this.x>player.x-this.offset-player.offset_x&&this.y>player.y-this.offset-player.offset_y&&this.x<player.x+this.offset+player.offset_x&&this.y<player.y+this.offset+player.offset_y&&(this.active=!1,13>=player.health?(player.health+=2,texts.push(new Text("+2 health",this.x,this.y,1500,{r:0,g:255,b:127}))):(player.ammo+=10,texts.push(new Text("+10 ammo",this.x,this.y,1500))))};
function Text(a,b,c,e,d){this.text=a;this.x=b-a.length/2*11;this.y=c;this.lifetime=e;this.life=0;this.active=!0;d?(this.r=d.r,this.g=d.g,this.b=d.b):(this.r=186,this.g=85,this.b=211);this.alpha=1}Text.prototype.update=function(a){this.life+=a;this.y-=.05*a;this.alpha=1-this.life/this.lifetime;this.life>=this.lifetime&&(this.active=!1)};var last_time=null,lapse=0,paused=!1,playing=!0;
function animate(a){lapse=null==last_time?0:a-last_time;last_time=a;!paused&&playing&&(cycle(lapse),null==spawn_time?(spawn_time=a,spawn_monster(a)):spawn_time<a&&spawn_monster(a));draw_frame();requestAnimationFrame(animate)}
function cycle(a){player.update(a);bullets=bullets.filter(function(a){return a.active});monsters=monsters.filter(function(a){return a.active});objects=objects.filter(function(a){return a.active});texts=texts.filter(function(a){return a.active});bullets.forEach(function(b){b.update(a)});monsters.forEach(function(b){b.update(a)});objects.forEach(function(b){b.update(a)});texts.forEach(function(b){b.update(a)})}
var player_sprite=function(){var a=document.createElement("img");a.src="sprites/player.png";return a}(),player_sprite_width=10,player_sprite_height=15,bullet_sprite=function(){var a=document.createElement("img");a.src="sprites/bullet.png";return a}(),monster_sprite=function(){var a=document.createElement("img");a.src="sprites/monster.png";return a}(),big_monster_sprite=function(){var a=document.createElement("img");a.src="sprites/big_monster.png";return a}(),crate_sprite=function(){var a=document.createElement("img");
a.src="sprites/crates.png";return a}();
function draw_frame(){context.clearRect(0,0,width,height);context.strokeStyle="lightslategray";context.beginPath();context.moveTo(200,0);context.lineTo(200,height);context.closePath();context.stroke();context.drawImage(player_sprite,0,2*player_sprite_height*player.pose,2*player_sprite_width,2*player_sprite_height,player.x-player.offset_x,player.y-player.offset_y,2*player.offset_x,2*player.offset_y);bullets.forEach(function(a){context.drawImage(bullet_sprite,a.x-3,a.y-2)});monsters.forEach(function(a){a instanceof
Monster&&context.drawImage(monster_sprite,0,2*a.offset*a.pose,2*a.offset,2*a.offset,a.x-a.offset,a.y-a.offset,2*a.offset,2*a.offset);a instanceof Big_monster&&(context.drawImage(big_monster_sprite,0,2*a.offset*a.pose,2*a.offset,2*a.offset,a.x-a.offset,a.y-a.offset,2*a.offset,2*a.offset),context.fillStyle="maroon",context.fillRect(a.x-a.offset,a.y-a.offset-8,6*a.health,5))});objects.forEach(function(a){a instanceof Ammo_box&&context.drawImage(crate_sprite,0,0,20,20,a.x-a.offset,a.y-a.offset,2*a.offset,
2*a.offset);a instanceof Health_box&&context.drawImage(crate_sprite,0,20,20,20,a.x-a.offset,a.y-a.offset,2*a.offset,2*a.offset)});texts.forEach(function(a){context.font="14pt Arial";context.fillStyle="rgba("+a.r+", "+a.g+", "+a.b+", "+a.alpha+")";context.fillText(a.text,a.x,a.y)});context.fillStyle="royalblue";context.font="12pt Arial";context.fillText(0==player.ammo&&0==objects.length&&0==bullets.length?"no ammo? you're screwed!":"ammo: "+player.ammo,5,30);context.fillText(0<player.health?"health: "+
player.health:"you're dead!",5,50);context.fillText("score: "+score,5,70)};
